### ISSUE TITLE
Hover tooltip width adjust

### ISSUE THREAD

**Issue by FergusDevelopmentLLC** [FergusDevelopmentLLC/names-map-node#17]
Hover window should be constrained to a certain width? ~400px? If that's wrapping SVG text it's a bit of a pain

**Comment by FergusDevelopmentLLC** [comment]
The hover is not svg, @rgdonohue . Are you suggesting that any line wrap and the hover should be a single 400px or less width box?

**Comment by rgdonohue** [comment]
Yeah, wrapping is a pain. This solution works though. https://bl.ocks.org/mbostock/7555321
This is a minor issue though. Maybe not worth the hassle.
