### ISSUE TITLE
Build out page layout a bit more

### ISSUE THREAD

**Issue by rgdonohue** [FergusDevelopmentLLC/names-map-node#4]
The current page looks quite clean and minimalist (which is often good). But perhaps a bit too minimal? Not that we want to load up the design with a bunch of ornamentation and "cart junk" (a la Edward Tufte), but here's some overall design considerations:

- center the map within the page using a container (but still max width ~960px or so)
- title a bit larger (maybe) and more line-height between the text upper left
- add more supplemental text/context about the map data (not even full paragraphs, but brief statements/bullet points)
- following from the previous bullet, suggest some interesting searches or patterns in the data for the user to explore (drawn from your README.md on the repo)

**Comment by FergusDevelopmentLLC** [comment]
Maybe a cheat, but I added an About this map link to a modal window to get some supplemental information presented. I updated the titles size and centered the map.

**Comment by FergusDevelopmentLLC** [comment]
closing this, please reopen if there is an issue.
